### ISSUE TITLE
[DOC] Notbook for smoothing transformers

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2269] opened 2024-10-29 10:33 UTC
### Describe the issue linked to the documentation

#1920 gave us a bunch of smoothing transformers, it would be nice to have a notebook to describe them and show uses

**Comment by MatthewMiddlehurst** [comment] 2024-10-29 12:39
duplicate of #2267?

**Closed** 2024-10-30 13:14 UTC
Labels: documentation, duplicate, transformations
